export const CURATE_ABI = [
  {
    type: "constructor",
    inputs: [
      { name: "royaltyModule", type: "address", internalType: "address" },
      { name: "tokenizerModule", type: "address", internalType: "address" },
      { name: "upgradeableBeacon", type: "address", internalType: "address" },
      { name: "ipAssetRegistry", type: "address", internalType: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "IP_ASSET_REGISTRY",
    inputs: [],
    outputs: [
      { name: "", type: "address", internalType: "contract IIPAssetRegistry" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "ROYALTY_MODULE",
    inputs: [],
    outputs: [
      { name: "", type: "address", internalType: "contract IRoyaltyModule" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "TOKENIZER_MODULE",
    inputs: [],
    outputs: [
      { name: "", type: "address", internalType: "contract ITokenizerModule" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "TOTAL_BIO_TOKEN_SUPPLY",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "UPGRADEABLE_BEACON",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "cancel",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "claimBioTokens",
    inputs: [{ name: "claimer", type: "address", internalType: "address" }],
    outputs: [
      { name: "bioToken", type: "address", internalType: "address" },
      { name: "amountClaimed", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "claimRefund",
    inputs: [],
    outputs: [{ name: "amount", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "close",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "deposit",
    inputs: [{ name: "amount", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "getAdmin",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getBioName",
    inputs: [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getBioToken",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getBioTokenName",
    inputs: [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getBioTokenSymbol",
    inputs: [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getBioTokensClaimable",
    inputs: [{ name: "user", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getDepositedAmount",
    inputs: [{ name: "user", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getExpirationTime",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getFundReceiver",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getIpId",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getMinimalIpTokenForLaunch",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getStakingContract",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getState",
    inputs: [],
    outputs: [
      { name: "", type: "uint8", internalType: "enum IAscCurate.State" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getTotalDeposited",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getTotalSupplyOfBioToken",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "getUpgradeableBeacon",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "initialize",
    inputs: [
      {
        name: "initData",
        type: "tuple",
        internalType: "struct IAscCurate.CurateInitData",
        components: [
          { name: "admin", type: "address", internalType: "address" },
          { name: "ipId", type: "address", internalType: "address" },
          { name: "ipNft", type: "address", internalType: "address" },
          { name: "ipNftTokenId", type: "uint256", internalType: "uint256" },
          { name: "expirationTime", type: "uint256", internalType: "uint256" },
          { name: "fundReceiver", type: "address", internalType: "address" },
          { name: "bioName", type: "string", internalType: "string" },
          { name: "bioTokenName", type: "string", internalType: "string" },
          { name: "bioTokenSymbol", type: "string", internalType: "string" },
          {
            name: "minimalIpTokenForLaunch",
            type: "uint256",
            internalType: "uint256",
          },
          { name: "rewardToken", type: "address", internalType: "address" },
        ],
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "launchProject",
    inputs: [
      { name: "bioTokenTemplate", type: "address", internalType: "address" },
      {
        name: "stakingContractTemplate",
        type: "address",
        internalType: "address",
      },
      {
        name: "initData",
        type: "tuple",
        internalType: "struct IAscStaking.InitData",
        components: [
          { name: "admin", type: "address", internalType: "address" },
          { name: "ipId", type: "address", internalType: "address" },
          {
            name: "rewardDistributionPeriod",
            type: "uint256",
            internalType: "uint256",
          },
          { name: "rewardToken", type: "address", internalType: "address" },
          {
            name: "bioTokenAllocPoints",
            type: "uint256",
            internalType: "uint256",
          },
        ],
      },
    ],
    outputs: [
      { name: "bioToken", type: "address", internalType: "address" },
      { name: "stakingContract", type: "address", internalType: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "onERC721Received",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "uint256", internalType: "uint256" },
      { name: "", type: "bytes", internalType: "bytes" },
    ],
    outputs: [{ name: "", type: "bytes4", internalType: "bytes4" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferAdminRole",
    inputs: [{ name: "newAdmin", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "withdraw",
    inputs: [],
    outputs: [
      { name: "withdrawnAmount", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "withdrawIp",
    inputs: [{ name: "recipient", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "AdminRoleTransferred",
    inputs: [
      {
        name: "previousAdmin",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newAdmin",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "BioTokenClaimed",
    inputs: [
      {
        name: "claimer",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amountClaimed",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  { type: "event", name: "CurateCanceled", inputs: [], anonymous: false },
  { type: "event", name: "CurateClosed", inputs: [], anonymous: false },
  {
    type: "event",
    name: "DepositReceived",
    inputs: [
      {
        name: "depositor",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Initialized",
    inputs: [
      {
        name: "version",
        type: "uint64",
        indexed: false,
        internalType: "uint64",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "IpWithdrawn",
    inputs: [
      {
        name: "recipient",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ProjectLaunched",
    inputs: [
      { name: "ipId", type: "address", indexed: true, internalType: "address" },
      {
        name: "bioToken",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "stakingContract",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RefundClaimed",
    inputs: [
      {
        name: "claimer",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "TokensWithdrawn",
    inputs: [
      {
        name: "receiver",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "error",
    name: "AscCurate__BioTokenAlreadyDeployed",
    inputs: [{ name: "bioToken", type: "address", internalType: "address" }],
  },
  { type: "error", name: "AscCurate__BioTokenNotSet", inputs: [] },
  {
    type: "error",
    name: "AscCurate__BioTokenSupplyLessThanTotalDeposits",
    inputs: [
      { name: "bioTokenTotalSupply", type: "uint256", internalType: "uint256" },
      { name: "totalDeposits", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "AscCurate__CallerNotAdmin",
    inputs: [
      { name: "caller", type: "address", internalType: "address" },
      { name: "admin", type: "address", internalType: "address" },
    ],
  },
  {
    type: "error",
    name: "AscCurate__ClaimerAlreadyClaimed",
    inputs: [{ name: "claimer", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "AscCurate__ClaimerNotEligible",
    inputs: [{ name: "claimer", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "AscCurate__CurateNotCanceled",
    inputs: [
      {
        name: "currentState",
        type: "uint8",
        internalType: "enum IAscCurate.State",
      },
    ],
  },
  {
    type: "error",
    name: "AscCurate__CurateNotClosed",
    inputs: [
      {
        name: "currentState",
        type: "uint8",
        internalType: "enum IAscCurate.State",
      },
    ],
  },
  {
    type: "error",
    name: "AscCurate__CurateNotOpen",
    inputs: [
      {
        name: "currentState",
        type: "uint8",
        internalType: "enum IAscCurate.State",
      },
    ],
  },
  {
    type: "error",
    name: "AscCurate__DepositAmountMismatch",
    inputs: [
      { name: "depositor", type: "address", internalType: "address" },
      { name: "providedAmount", type: "uint256", internalType: "uint256" },
      { name: "actualAmount", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "AscCurate__ExpirationTimeNotInFuture",
    inputs: [
      { name: "expirationTime", type: "uint256", internalType: "uint256" },
      { name: "currentTime", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "AscCurate__IpNotRegistered",
    inputs: [
      { name: "ipNft", type: "address", internalType: "address" },
      { name: "ipNftTokenId", type: "uint256", internalType: "uint256" },
      { name: "ipId", type: "address", internalType: "address" },
    ],
  },
  {
    type: "error",
    name: "AscCurate__IpNotTransferredToCurate",
    inputs: [
      { name: "ipId", type: "address", internalType: "address" },
      { name: "ipNft", type: "address", internalType: "address" },
      { name: "ipNftTokenId", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "AscCurate__IpRoyaltyVaultNotDeployed",
    inputs: [{ name: "ipId", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "AscCurate__IpRoyaltyVaultTransferFailed",
    inputs: [
      { name: "ascVault", type: "address", internalType: "address" },
      { name: "ipId", type: "address", internalType: "address" },
    ],
  },
  {
    type: "error",
    name: "AscCurate__NoRefundableDeposit",
    inputs: [{ name: "claimer", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "AscCurate__RefundClaimFailed",
    inputs: [
      { name: "claimer", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "AscCurate__TotalDepositsLessThanMinimumTotalDeposits",
    inputs: [
      { name: "totalDeposits", type: "uint256", internalType: "uint256" },
      {
        name: "minimumTotalDeposits",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "AscCurate__WithdrawFailed",
    inputs: [
      { name: "withdrawnAmount", type: "uint256", internalType: "uint256" },
    ],
  },
  { type: "error", name: "AscCurate__ZeroAdminAddress", inputs: [] },
  { type: "error", name: "AscCurate__ZeroFundReceiverAddress", inputs: [] },
  { type: "error", name: "AscCurate__ZeroIpAssetRegistryAddress", inputs: [] },
  { type: "error", name: "AscCurate__ZeroIpIdAddress", inputs: [] },
  { type: "error", name: "AscCurate__ZeroIpNftAddress", inputs: [] },
  { type: "error", name: "AscCurate__ZeroIpNftTokenId", inputs: [] },
  { type: "error", name: "AscCurate__ZeroRoyaltyModuleAddress", inputs: [] },
  { type: "error", name: "AscCurate__ZeroTokenizerModuleAddress", inputs: [] },
  {
    type: "error",
    name: "AscCurate__ZeroUpgradeableBeaconAddress",
    inputs: [],
  },
  { type: "error", name: "InvalidInitialization", inputs: [] },
  { type: "error", name: "NotInitializing", inputs: [] },
  { type: "error", name: "ReentrancyGuardReentrantCall", inputs: [] },
];
